using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using UserManagementAPI.Infrastructure.Outbox;

namespace UserManagementAPI.Infrastructure.Persistence.Configurations;

internal sealed class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
{
    public void Configure(EntityTypeBuilder<OutboxMessage> builder)
    {
        builder.ToTable("outbox_messages");

        builder.HasKey(message => message.Id);

        // The writer assigns the id; nothing is generated by EF Core or the database.
        builder.Property(message => message.Id).ValueGeneratedNever();

        builder.Property(message => message.Type)
            .HasMaxLength(500)
            .IsRequired();

        builder.Property(message => message.Payload)
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(message => message.OccurredOnUtc).IsRequired();
        builder.Property(message => message.Attempts).IsRequired();

        builder.Property(message => message.Error)
            .HasMaxLength(OutboxMessage.MaxErrorLength);

        // The poll reads unprocessed rows in occurrence order. A partial index
        // over exactly those rows stays tiny however large the table grows,
        // because processed rows drop out of it.
        builder.HasIndex(message => message.OccurredOnUtc)
            .HasDatabaseName("ix_outbox_messages_pending")
            .HasFilter("processed_on_utc IS NULL");
    }
}